server:
  address: 127.0.0.1
  port: 8080
  context-path: ""

security:
  basic.enabled: false
  basic.realm: "MoneyTrack Development Basic Authroisation Realm"

spring:
  application.name: MoneyTracker
  http:
    encoding.charset: UTF=8
    encoding.enabled: true

spring:
    datasource:
        driverClassName: org.hsqldb.jdbcDriver
        url: jdbc:hsqldb:mem:moneyTrak
        username: sa
        password:
    jpa:
      database-platform: org.hibernate.dialect.HSQLDialect
      show-sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: true
        hibernate.generate_statistics: true


#spring:
#  batch:
#    job.enabled: true
#    job.names: "Names"
