spring:
  application.name: MoneyTracker
  profiles.active: development

server:
  address: 127.0.0.1
  port: 8080
  sessionTimeout: 30
  context-path: ""

spring:
  data:
    mongodb.host: localhost
    mongodb.port: 27017
#    mogodb.uri: mongodb://localhost/MoneyTracker
