spring:
  application.name: MoneyTracker
  profiles.active: development

server:
  address: 127.0.0.1
  port: 8080
  sessionTimeout: 30
  context-path: ""

spring:
  data:
    mongodb.host: 127.0.0.1
    mongodb.port: 27017
#    mongodb.uri: "mongodb://localhost/test"
#    mongodb.database: "moneyTracker"
#    mongodb.gridFsDatabase: ""
#    mongodb.username:
#    mongodb.password:

#spring:
#  batch:
#    job.enabled: true
#    job.names: "Names"